FROM golang:1.23

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client && apt-get clean

COPY go.mod go.sum ./

RUN go mod download

COPY . .

ENTRYPOINT ["go", "test", "./tests/...", "-v"]